# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGNkY-_mqOKRFA-JaLvtawwvQ3aMoeqh
"""

from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
  return "Hello Flask, CI/CD"

if __name__ == "__main__":
  app.run(debug = True)

